if (NOT CMAKE_SCRIPT_MODE_FILE)
   set(ERU_SHADER_STRUCTURE_ROOTS "" CACHE STRING "Additional source roots searched for shader structures")

   function (generate_shader_structures)
      # The argument-less deferred call creates the target after all project and plugin
      # directories have been declared. Keeping it here avoids exposing helper commands.
      if (ARGC EQUAL 0)
         get_property(TARGET_NAME GLOBAL PROPERTY ERU_SHADER_STRUCTURES_TARGET)
         get_property(OUTPUT_DIRECTORY GLOBAL PROPERTY ERU_SHADER_STRUCTURES_OUTPUT_DIRECTORY)
         get_property(GENERATOR GLOBAL PROPERTY ERU_SHADER_STRUCTURES_GENERATOR)

         get_property(SOURCE_ROOTS DIRECTORY "${CMAKE_SOURCE_DIR}" PROPERTY SUBDIRECTORIES)
         list(APPEND SOURCE_ROOTS "${CMAKE_SOURCE_DIR}" ${ERU_SHADER_STRUCTURE_ROOTS})
         list(REMOVE_DUPLICATES SOURCE_ROOTS)
         list(JOIN SOURCE_ROOTS "|" ENCODED_SOURCE_ROOTS)

         set(OUTPUT "${OUTPUT_DIRECTORY}/structures.slang")
         set(GENERATOR_TARGET "${TARGET_NAME}_shader_structures")

         add_custom_target(${GENERATOR_TARGET}
            COMMAND "${CMAKE_COMMAND}"
            "-DERU_SHADER_STRUCTURES_OUTPUT=${OUTPUT}"
            "-DERU_SHADER_STRUCTURE_ROOTS=${ENCODED_SOURCE_ROOTS}"
            -P "${GENERATOR}"
            BYPRODUCTS "${OUTPUT}"
            DEPENDS "${GENERATOR}"
            COMMENT "Generating shared C++/Slang structures"
            VERBATIM)
         add_dependencies(${TARGET_NAME} ${GENERATOR_TARGET})
         return()
      endif ()

      if (NOT ARGC EQUAL 2)
         message(FATAL_ERROR "generate_shader_structures expects a target and an output directory")
      endif ()

      set(TARGET_NAME "${ARGV0}")
      set(OUTPUT_DIRECTORY "${ARGV1}")

      if (NOT TARGET ${TARGET_NAME})
         message(FATAL_ERROR "generate_shader_structures target does not exist (${TARGET_NAME})")
      endif ()

      get_property(ALREADY_CONFIGURED GLOBAL PROPERTY ERU_SHADER_STRUCTURES_TARGET SET)
      if (ALREADY_CONFIGURED)
         message(FATAL_ERROR "generate_shader_structures may only be called once")
      endif ()

      get_filename_component(OUTPUT_DIRECTORY "${OUTPUT_DIRECTORY}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
      set_property(GLOBAL PROPERTY ERU_SHADER_STRUCTURES_TARGET "${TARGET_NAME}")
      set_property(GLOBAL PROPERTY ERU_SHADER_STRUCTURES_OUTPUT_DIRECTORY "${OUTPUT_DIRECTORY}")
      set_property(GLOBAL PROPERTY ERU_SHADER_STRUCTURES_GENERATOR "${CMAKE_CURRENT_FUNCTION_LIST_FILE}")

      cmake_language(DEFER DIRECTORY "${CMAKE_SOURCE_DIR}" CALL generate_shader_structures)
   endfunction ()

   return()
endif ()

cmake_minimum_required(VERSION 3.19)

if (NOT DEFINED ERU_SHADER_STRUCTURES_OUTPUT OR NOT DEFINED ERU_SHADER_STRUCTURE_ROOTS)
   message(FATAL_ERROR "shader_structures.cmake requires output and source-root arguments")
endif ()

string(REPLACE "|" ";" SOURCE_ROOTS "${ERU_SHADER_STRUCTURE_ROOTS}")
set(CPP_EXTENSIONS .c .cc .cpp .cppm .cxx .h .hh .hpp .hxx .inc .inl .ixx)
set(IGNORED_DIRECTORIES .git .idea .vs build out vcpkg vcpkg_installed)

function (collect_cpp_sources DIRECTORY OUTPUT_VARIABLE)
   set(RESULT)
   file(GLOB ENTRIES LIST_DIRECTORIES TRUE "${DIRECTORY}/*")
   foreach (ENTRY IN LISTS ENTRIES)
      if (IS_DIRECTORY "${ENTRY}")
         if (IS_SYMLINK "${ENTRY}")
            continue()
         endif ()
         get_filename_component(NAME "${ENTRY}" NAME)
         string(TOLOWER "${NAME}" LOWER_NAME)
         if (LOWER_NAME IN_LIST IGNORED_DIRECTORIES OR LOWER_NAME MATCHES "^cmake-build-")
            continue()
         endif ()
         collect_cpp_sources("${ENTRY}" CHILD_SOURCES)
         list(APPEND RESULT ${CHILD_SOURCES})
      else ()
         get_filename_component(EXTENSION "${ENTRY}" EXT)
         string(TOLOWER "${EXTENSION}" EXTENSION)
         if (EXTENSION IN_LIST CPP_EXTENSIONS)
            get_filename_component(ENTRY "${ENTRY}" ABSOLUTE)
            list(APPEND RESULT "${ENTRY}")
         endif ()
      endif ()
   endforeach ()
   set(${OUTPUT_VARIABLE} ${RESULT} PARENT_SCOPE)
endfunction ()

function (source_line CONTENT NEEDLE OUTPUT_VARIABLE)
   string(FIND "${CONTENT}" "${NEEDLE}" POSITION)
   if (POSITION LESS 0)
      set(${OUTPUT_VARIABLE} 1 PARENT_SCOPE)
      return()
   endif ()
   string(SUBSTRING "${CONTENT}" 0 ${POSITION} PREFIX)
   string(REGEX MATCHALL "\n" NEWLINES "${PREFIX}")
   list(LENGTH NEWLINES LINE)
   math(EXPR LINE "${LINE} + 1")
   set(${OUTPUT_VARIABLE} ${LINE} PARENT_SCOPE)
endfunction ()

function (without_comments CONTENT OUTPUT_VARIABLE)
   string(REGEX REPLACE "//[^\n]*" "" CONTENT "${CONTENT}")
   set(BLOCK_COMMENT_PATTERN "/\\*([^*]|\\*+[^*/])*\\*+/")
   while (CONTENT MATCHES "${BLOCK_COMMENT_PATTERN}")
      string(REGEX MATCH "${BLOCK_COMMENT_PATTERN}" COMMENT "${CONTENT}")
      string(REGEX MATCHALL "\n" COMMENT_NEWLINES "${COMMENT}")
      list(LENGTH COMMENT_NEWLINES COMMENT_NEWLINE_COUNT)
      string(REPEAT "\n" ${COMMENT_NEWLINE_COUNT} COMMENT_REPLACEMENT)
      string(REPLACE "${COMMENT}" "${COMMENT_REPLACEMENT}" CONTENT "${CONTENT}")
   endwhile ()
   set(${OUTPUT_VARIABLE} "${CONTENT}" PARENT_SCOPE)
endfunction ()

function (slang_type CPP_TYPE ARRAY_COUNT KNOWN_TYPES SOURCE LINE OUTPUT_TYPE OUTPUT_DEPENDENCY OUTPUT_ERROR)
   string(REGEX REPLACE "[ \t\r\n]+" " " CPP_TYPE "${CPP_TYPE}")
   string(STRIP "${CPP_TYPE}" CPP_TYPE)
   set(${OUTPUT_ERROR} "" PARENT_SCOPE)

   if (CPP_TYPE STREQUAL "double")
      set(${OUTPUT_ERROR} "${SOURCE}:${LINE}: 'double' is not supported by this Vulkan scalar layout" PARENT_SCOPE)
      return()
   endif ()
   if (CPP_TYPE STREQUAL "bool" AND NOT "${ARRAY_COUNT}" STREQUAL "")
      set(${OUTPUT_ERROR} "${SOURCE}:${LINE}: bool arrays are not layout-compatible with std::array<bool, N>; use std::uint32_t instead" PARENT_SCOPE)
      return()
   endif ()

   if (CPP_TYPE STREQUAL "bool")
      set(SLANG_TYPE bool)
   elseif (CPP_TYPE STREQUAL "float")
      set(SLANG_TYPE float)
   elseif (CPP_TYPE STREQUAL "std::int32_t" OR CPP_TYPE STREQUAL "int32_t")
      set(SLANG_TYPE int)
   elseif (CPP_TYPE STREQUAL "std::uint32_t" OR CPP_TYPE STREQUAL "uint32_t")
      set(SLANG_TYPE uint)
   elseif (CPP_TYPE STREQUAL "glm::vec2")
      set(SLANG_TYPE float2)
   elseif (CPP_TYPE STREQUAL "glm::vec3")
      set(SLANG_TYPE float3)
   elseif (CPP_TYPE STREQUAL "glm::vec4")
      set(SLANG_TYPE float4)
   elseif (CPP_TYPE STREQUAL "glm::ivec2")
      set(SLANG_TYPE int2)
   elseif (CPP_TYPE STREQUAL "glm::ivec3")
      set(SLANG_TYPE int3)
   elseif (CPP_TYPE STREQUAL "glm::ivec4")
      set(SLANG_TYPE int4)
   elseif (CPP_TYPE STREQUAL "glm::uvec2")
      set(SLANG_TYPE uint2)
   elseif (CPP_TYPE STREQUAL "glm::uvec3")
      set(SLANG_TYPE uint3)
   elseif (CPP_TYPE STREQUAL "glm::uvec4")
      set(SLANG_TYPE uint4)
   elseif (CPP_TYPE STREQUAL "glm::mat2")
      set(SLANG_TYPE float2x2)
   elseif (CPP_TYPE STREQUAL "glm::mat3")
      set(SLANG_TYPE float3x3)
   elseif (CPP_TYPE STREQUAL "glm::mat4")
      set(SLANG_TYPE float4x4)
   else ()
      string(REGEX REPLACE "^::" "" SLANG_TYPE "${CPP_TYPE}")
      string(REGEX REPLACE "^.*::" "" SLANG_TYPE "${SLANG_TYPE}")
      if (NOT SLANG_TYPE MATCHES "^[A-Za-z_][A-Za-z0-9_]*$" OR
         NOT SLANG_TYPE IN_LIST KNOWN_TYPES)
         set(${OUTPUT_ERROR} "${SOURCE}:${LINE}: unsupported shader field type '${CPP_TYPE}'" PARENT_SCOPE)
         return()
      endif ()
      set(${OUTPUT_DEPENDENCY} "${SLANG_TYPE}" PARENT_SCOPE)
   endif ()

   set(${OUTPUT_TYPE} "${SLANG_TYPE}" PARENT_SCOPE)
endfunction ()

set(SOURCES)
foreach (ROOT IN LISTS SOURCE_ROOTS)
   if (IS_DIRECTORY "${ROOT}")
      collect_cpp_sources("${ROOT}" ROOT_SOURCES)
      list(APPEND SOURCES ${ROOT_SOURCES})
   endif ()
endforeach ()
list(REMOVE_DUPLICATES SOURCES)
list(SORT SOURCES)

set(RECORD_COUNT 0)
set(STRUCTURE_NAMES)
set(STRUCTURE_PATTERN "ERU_SHADER_STRUCTURE\\([ \t]*[A-Za-z_][A-Za-z0-9_]*[ \t]*\\)[ \t\r\n]*\\{[^}]*\\}")
set(FIELD_CALL_PATTERN "ERU_SHADER_(ARRAY_)?FIELD\\([^)]*\\)")

foreach (SOURCE IN LISTS SOURCES)
   file(READ "${SOURCE}" ORIGINAL)

   without_comments("${ORIGINAL}" CONTENT)

   set(SEARCH "${CONTENT}")
   set(SEARCH_LINE_BASE 1)
   while (SEARCH MATCHES "${STRUCTURE_PATTERN}")
      string(REGEX MATCH "${STRUCTURE_PATTERN}" DECLARATION "${SEARCH}")
      string(REGEX MATCH "ERU_SHADER_STRUCTURE\\([ \t]*([A-Za-z_][A-Za-z0-9_]*)[ \t]*\\)" NAME_MATCH "${DECLARATION}")
      set(NAME "${CMAKE_MATCH_1}")
      source_line("${SEARCH}" "${DECLARATION}" RELATIVE_RECORD_LINE)
      math(EXPR RECORD_LINE "${SEARCH_LINE_BASE} + ${RELATIVE_RECORD_LINE} - 1")

      if (NAME IN_LIST STRUCTURE_NAMES)
         list(FIND STRUCTURE_NAMES "${NAME}" PREVIOUS_INDEX)
         set(PREVIOUS_SOURCE_VARIABLE "RECORD_${PREVIOUS_INDEX}_SOURCE")
         set(PREVIOUS_LINE_VARIABLE "RECORD_${PREVIOUS_INDEX}_LINE")
         message(FATAL_ERROR "${SOURCE}:${RECORD_LINE}: shader structure '${NAME}' was already declared at ${${PREVIOUS_SOURCE_VARIABLE}}:${${PREVIOUS_LINE_VARIABLE}}")
      endif ()

      string(FIND "${DECLARATION}" "{" BODY_START)
      math(EXPR BODY_START "${BODY_START} + 1")
      string(LENGTH "${DECLARATION}" DECLARATION_LENGTH)
      math(EXPR BODY_LENGTH "${DECLARATION_LENGTH} - ${BODY_START} - 1")
      string(SUBSTRING "${DECLARATION}" ${BODY_START} ${BODY_LENGTH} BODY)

      set(REMAINDER "${BODY}")
      string(REGEX MATCHALL "${FIELD_CALL_PATTERN}" FIELD_CALLS "${BODY}")
      list(LENGTH FIELD_CALLS FIELD_COUNT)
      if (FIELD_COUNT EQUAL 0)
         message(FATAL_ERROR "${SOURCE}:${RECORD_LINE}: shader structures cannot be empty")
      endif ()

      set(FIELD_INDEX 0)
      set(FIELD_SEARCH "${DECLARATION}")
      set(FIELD_LINE_BASE ${RECORD_LINE})
      foreach (FIELD_CALL IN LISTS FIELD_CALLS)
         source_line("${FIELD_SEARCH}" "${FIELD_CALL}" RELATIVE_FIELD_LINE)
         math(EXPR FIELD_LINE "${FIELD_LINE_BASE} + ${RELATIVE_FIELD_LINE} - 1")
         string(REPLACE "${FIELD_CALL}" "" REMAINDER "${REMAINDER}")

         if (FIELD_CALL MATCHES
            "^ERU_SHADER_FIELD\\([ \t\r\n]*([^,]+),[ \t\r\n]*([A-Za-z_][A-Za-z0-9_]*)[ \t\r\n]*\\)$")
            set(FIELD_TYPE "${CMAKE_MATCH_1}")
            set(FIELD_NAME "${CMAKE_MATCH_2}")
            set(ARRAY_COUNT "")
         elseif (FIELD_CALL MATCHES
            "^ERU_SHADER_ARRAY_FIELD\\([ \t\r\n]*([^,]+),[ \t\r\n]*([1-9][0-9]*),[ \t\r\n]*([A-Za-z_][A-Za-z0-9_]*)[ \t\r\n]*\\)$")
            set(FIELD_TYPE "${CMAKE_MATCH_1}")
            set(ARRAY_COUNT "${CMAKE_MATCH_2}")
            set(FIELD_NAME "${CMAKE_MATCH_3}")
         else ()
            message(FATAL_ERROR "${SOURCE}:${FIELD_LINE}: malformed shader field declaration")
         endif ()
         string(STRIP "${FIELD_TYPE}" FIELD_TYPE)

         set(FIELD_NAMES_VARIABLE "RECORD_${RECORD_COUNT}_FIELD_NAMES")
         if (FIELD_NAME IN_LIST ${FIELD_NAMES_VARIABLE})
            message(FATAL_ERROR "${SOURCE}:${FIELD_LINE}: duplicate field '${FIELD_NAME}'")
         endif ()
         list(APPEND ${FIELD_NAMES_VARIABLE} "${FIELD_NAME}")

         set("RECORD_${RECORD_COUNT}_FIELD_${FIELD_INDEX}_TYPE" "${FIELD_TYPE}")
         set("RECORD_${RECORD_COUNT}_FIELD_${FIELD_INDEX}_NAME" "${FIELD_NAME}")
         set("RECORD_${RECORD_COUNT}_FIELD_${FIELD_INDEX}_COUNT" "${ARRAY_COUNT}")
         set("RECORD_${RECORD_COUNT}_FIELD_${FIELD_INDEX}_LINE" "${FIELD_LINE}")
         math(EXPR FIELD_INDEX "${FIELD_INDEX} + 1")

         string(FIND "${FIELD_SEARCH}" "${FIELD_CALL}" FIELD_POSITION)
         string(LENGTH "${FIELD_CALL}" FIELD_MATCH_LENGTH)
         math(EXPR FIELD_NEXT_POSITION "${FIELD_POSITION} + ${FIELD_MATCH_LENGTH}")
         string(SUBSTRING "${FIELD_SEARCH}" 0 ${FIELD_NEXT_POSITION} FIELD_CONSUMED)
         string(REGEX MATCHALL "\n" FIELD_NEWLINES "${FIELD_CONSUMED}")
         list(LENGTH FIELD_NEWLINES FIELD_NEWLINE_COUNT)
         math(EXPR FIELD_LINE_BASE "${FIELD_LINE_BASE} + ${FIELD_NEWLINE_COUNT}")
         string(SUBSTRING "${FIELD_SEARCH}" ${FIELD_NEXT_POSITION} -1 FIELD_SEARCH)
      endforeach ()

      string(REGEX REPLACE "[ \t\r\n;]" "" REMAINDER "${REMAINDER}")
      if (NOT REMAINDER STREQUAL "")
         message(FATAL_ERROR "${SOURCE}:${RECORD_LINE}: shader structures may contain only ERU_SHADER_FIELD and ERU_SHADER_ARRAY_FIELD declarations")
      endif ()

      set("RECORD_${RECORD_COUNT}_NAME" "${NAME}")
      set("RECORD_${RECORD_COUNT}_SOURCE" "${SOURCE}")
      set("RECORD_${RECORD_COUNT}_LINE" "${RECORD_LINE}")
      set("RECORD_${RECORD_COUNT}_FIELD_COUNT" "${FIELD_COUNT}")
      list(APPEND STRUCTURE_NAMES "${NAME}")
      math(EXPR RECORD_COUNT "${RECORD_COUNT} + 1")

      string(FIND "${SEARCH}" "${DECLARATION}" DECLARATION_POSITION)
      string(LENGTH "${DECLARATION}" MATCH_LENGTH)
      math(EXPR NEXT_POSITION "${DECLARATION_POSITION} + ${MATCH_LENGTH}")
      string(SUBSTRING "${SEARCH}" 0 ${NEXT_POSITION} SEARCH_CONSUMED)
      string(REGEX MATCHALL "\n" SEARCH_NEWLINES "${SEARCH_CONSUMED}")
      list(LENGTH SEARCH_NEWLINES SEARCH_NEWLINE_COUNT)
      math(EXPR SEARCH_LINE_BASE "${SEARCH_LINE_BASE} + ${SEARCH_NEWLINE_COUNT}")
      string(SUBSTRING "${SEARCH}" ${NEXT_POSITION} -1 SEARCH)
   endwhile ()
endforeach ()

if (RECORD_COUNT GREATER 0)
   math(EXPR LAST_RECORD "${RECORD_COUNT} - 1")
   foreach (RECORD_INDEX RANGE ${LAST_RECORD})
      set(FIELD_COUNT_VARIABLE "RECORD_${RECORD_INDEX}_FIELD_COUNT")
      set(RECORD_SOURCE_VARIABLE "RECORD_${RECORD_INDEX}_SOURCE")
      math(EXPR LAST_FIELD "${${FIELD_COUNT_VARIABLE}} - 1")
      foreach (FIELD_INDEX RANGE ${LAST_FIELD})
         set(TYPE_VARIABLE "RECORD_${RECORD_INDEX}_FIELD_${FIELD_INDEX}_TYPE")
         set(COUNT_VARIABLE "RECORD_${RECORD_INDEX}_FIELD_${FIELD_INDEX}_COUNT")
         set(LINE_VARIABLE "RECORD_${RECORD_INDEX}_FIELD_${FIELD_INDEX}_LINE")
         slang_type("${${TYPE_VARIABLE}}" "${${COUNT_VARIABLE}}" "${STRUCTURE_NAMES}"
            "${${RECORD_SOURCE_VARIABLE}}" "${${LINE_VARIABLE}}"
            MAPPED_TYPE DEPENDENCY TYPE_ERROR)
         if (TYPE_ERROR)
            message(FATAL_ERROR "${TYPE_ERROR}")
         endif ()
         set("RECORD_${RECORD_INDEX}_FIELD_${FIELD_INDEX}_SLANG_TYPE" "${MAPPED_TYPE}")
         if (DEFINED DEPENDENCY AND NOT DEPENDENCY STREQUAL "")
            list(APPEND "RECORD_${RECORD_INDEX}_DEPENDENCIES" "${DEPENDENCY}")
         endif ()
         unset(DEPENDENCY)
      endforeach ()
   endforeach ()
endif ()

set(REMAINING)
if (RECORD_COUNT GREATER 0)
   foreach (RECORD_INDEX RANGE ${LAST_RECORD})
      list(APPEND REMAINING ${RECORD_INDEX})
   endforeach ()
endif ()
set(ORDER)
set(EMITTED_NAMES)
list(LENGTH REMAINING REMAINING_COUNT)
while (REMAINING_COUNT GREATER 0)
   set(READY)
   foreach (RECORD_INDEX IN LISTS REMAINING)
      set(DEPENDENCIES_VARIABLE "RECORD_${RECORD_INDEX}_DEPENDENCIES")
      set(IS_READY TRUE)
      foreach (DEPENDENCY IN LISTS ${DEPENDENCIES_VARIABLE})
         if (NOT DEPENDENCY IN_LIST EMITTED_NAMES)
            set(IS_READY FALSE)
         endif ()
      endforeach ()
      if (IS_READY)
         list(APPEND READY ${RECORD_INDEX})
      endif ()
   endforeach ()

   list(LENGTH READY READY_COUNT)
   if (READY_COUNT EQUAL 0)
      set(LOCATIONS)
      foreach (RECORD_INDEX IN LISTS REMAINING)
         set(SOURCE_VARIABLE "RECORD_${RECORD_INDEX}_SOURCE")
         set(LINE_VARIABLE "RECORD_${RECORD_INDEX}_LINE")
         list(APPEND LOCATIONS "${${SOURCE_VARIABLE}}:${${LINE_VARIABLE}}")
      endforeach ()
      list(JOIN LOCATIONS ", " LOCATIONS)
      message(FATAL_ERROR
         "${LOCATIONS}: shader structures contain a by-value dependency cycle")
   endif ()

   foreach (RECORD_INDEX IN LISTS READY)
      list(APPEND ORDER ${RECORD_INDEX})
      set(NAME_VARIABLE "RECORD_${RECORD_INDEX}_NAME")
      list(APPEND EMITTED_NAMES "${${NAME_VARIABLE}}")
      list(REMOVE_ITEM REMAINING ${RECORD_INDEX})
   endforeach ()
   list(LENGTH REMAINING REMAINING_COUNT)
endwhile ()

string(CONCAT OUTPUT_CONTENT
   "// Auto-generated from C++ ERU_SHADER_STRUCTURE macros - do not edit"
   "\n"
   "\n#ifndef ERU_STRUCTURES"
   "\n#define ERU_STRUCTURES"
   "\n")

foreach (RECORD_INDEX IN LISTS ORDER)
   set(NAME_VARIABLE "RECORD_${RECORD_INDEX}_NAME")
   set(FIELD_COUNT_VARIABLE "RECORD_${RECORD_INDEX}_FIELD_COUNT")
   string(APPEND OUTPUT_CONTENT "\nstruct ${${NAME_VARIABLE}}\n{\n")
   math(EXPR LAST_FIELD "${${FIELD_COUNT_VARIABLE}} - 1")
   foreach (FIELD_INDEX RANGE ${LAST_FIELD})
      set(TYPE_VARIABLE "RECORD_${RECORD_INDEX}_FIELD_${FIELD_INDEX}_SLANG_TYPE")
      set(NAME_VARIABLE "RECORD_${RECORD_INDEX}_FIELD_${FIELD_INDEX}_NAME")
      set(COUNT_VARIABLE "RECORD_${RECORD_INDEX}_FIELD_${FIELD_INDEX}_COUNT")
      if ("${${COUNT_VARIABLE}}" STREQUAL "")
         set(ARRAY_SUFFIX "")
      else ()
         set(ARRAY_SUFFIX "[${${COUNT_VARIABLE}}]")
      endif ()
      string(APPEND OUTPUT_CONTENT
         "   ${${TYPE_VARIABLE}} ${${NAME_VARIABLE}}${ARRAY_SUFFIX};\n")
   endforeach ()
   string(APPEND OUTPUT_CONTENT "};\n")
endforeach ()
string(APPEND OUTPUT_CONTENT "\n#endif")

set(PREVIOUS_CONTENT)
if (EXISTS "${ERU_SHADER_STRUCTURES_OUTPUT}")
   file(READ "${ERU_SHADER_STRUCTURES_OUTPUT}" PREVIOUS_CONTENT)
endif ()
if (NOT PREVIOUS_CONTENT STREQUAL OUTPUT_CONTENT)
   get_filename_component(OUTPUT_DIRECTORY "${ERU_SHADER_STRUCTURES_OUTPUT}" DIRECTORY)
   file(MAKE_DIRECTORY "${OUTPUT_DIRECTORY}")
   file(WRITE "${ERU_SHADER_STRUCTURES_OUTPUT}" "${OUTPUT_CONTENT}")
endif ()

message(STATUS "Generated ${RECORD_COUNT} shader structure(s) into ${ERU_SHADER_STRUCTURES_OUTPUT}")
